version: "3"
services:
  postgresql:
    image: "postgres:13"
    environment:
      POSTGRES_DB: "noisli"
      POSTGRES_USER: "noisli"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
